#设置端口号
server:
  port: 8899
#设置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/he_ma_test
    username: root
    password: zxc85167518
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池设置
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: zxc85167518
        reset-enable: false
  servlet:
    multipart:
      max-file-size: 15MB
  redis:
    host: 1.117.156.11
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
pool:
 #核心线程池
 corePoolsize: 16
 #最大线程池
 maxPoolSize: 40
 #活跃时间
 keepAliveSeconds: 300
 #队列容量
 queueCapacity: 10
#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #日志查看sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDelete

constants:
  filePath: C:\Users\lh\Desktop\static\images\
  goodImgPath: C:\Users\lh\Desktop\static\goods-img\
