#设置端口号
server:
  port: 8899

#设置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/he_ma
    username: root
    password: zxc85167518
    driver-class-name: com.mysql.cj.jdbc.Driver

    #连接池设置
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: zxc85167518
        reset-enable: false


#mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDelete

